### 소설 등록
POST {{host}}/novel
Content-Type: application/json

{
  "title": "나 혼자만 개발자",
  "category": "FANTASY",
  "authorId": "1"
}

### 소설 한편 작성
POST {{host}}/novel/1
Content-Type: application/json

{
  "content": "이 세상에는 개발자가 나 한 명 밖에 없다."
}

### 소설 삭제
DELETE {{host}}/novel/1


### 선호작 등록
POST {{host}}/favorite
Content-Type: application/json

{
  "novelId": "1",
  "readerId": "1"
}

### 선호작 목록 조회
GET {{host}}/favorite
Content-Type: application/json

{
  "readerId": "1"
}
